### PR TITLE
Add EditUserParserTest

### PR DESCRIPTION
**Pull request by chrisjwelly**
**DO NOT MERGE YET UNTIL I WRITE HUNG'S SUGGESTIONS**
Note that I left out checking for DisplayPicture because for the parser to succeed, the file pointed by the path must actually exist.

The general method I tested this is:
* Change everything at once
* Change half of the things
* Change everything one by one
* The invalid commands

### CODE REVIEW

**Comment by nhamhung** [comment]
So nice!! :blush: :blush: The only thing I can think of is maybe for the last test with an invalid prefixed value, the test can also be like there is only one invalid and multiple valid but the error still thrown. Just saying something to be constructive haha but it's definitely LGTM (legitimate)

**Comment by chrisjwelly** [comment]
Thanks for the suggestions @nhamhung , I'm on it.

**Review by helloImHai — APPROVED** [review]
Clean and I love it 🛀🛀🛀

**Review by helloImHai — APPROVED** [review]
As it should be m8 💯💯💯
After the build fix

**Pull request merged**
